use_frameworks!

platform :ios, '9.0'

target 'AXZoomView_Example' do
  pod 'AXZoomView', :path => '../'

  target 'AXZoomView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
